### ISSUE TITLE
Parser - getShortName verbessern

### ISSUE THREAD

**Issue by Patdue** [JonnyBurger/Bestande#16]
Da einige Computerlinguistik Module mit "CL GV", "CL AV" oder "CL GV", teilweise gefolgt von einem ":" beginnen, werden die Shortnames dieser Module falsch geparst. Vielen Dank für die App ;-)

**Comment by Patdue** [comment]
Selbes Problem bei Jus Seminaren die mit "Seminar:" beginnen

**Comment by JonnyBurger** [comment]
Herzlichen Dank für den Hinweis! 
Ich versuche in dem Fall, den Algorithmus in den nächsten Tagen zu verbessern. Es scheint, als ob in nicht-WWF-Fakultäten das Problem noch viel grösser ist.

**Comment by JonnyBurger** [comment]
Sollte jetzt viel besser funktionieren!
Wenn es doch noch Probleme gibt, kannst du sie gerne melden!

**Comment by Patdue** [comment]
Vielen Dank für den schnellen fix! 👍
